services:
  - type: web
    name: trip_planner
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y openjdk-11-jdk
      pip install -r requirements.txt
    startCommand: gunicorn --chdir src app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-11-openjdk-amd64
      - key: PATH
        value: /usr/lib/jvm/java-11-openjdk-amd64/bin:${PATH}